### ISSUE TITLE
What does this software translate?

### ISSUE THREAD

**Issue by BSVogler** [yushijinhun/MCZHConverter#4]
First I thought it translates the map to another format. I think you mean language translation. Which languages are supported?

**Comment by yushijinhun** [comment]
> I think you mean language translation.

You're right. This software helps you translate a map into another language (e.g. English->Chinese). 

> Which languages are supported?

Translating cannot be done by machine anyway. What the software actually does is to extract the texts in the map and show them to you. When you finish translating, it writes your translations back. It's just a tool that helps you focus on translating but cannot really translate the texts. Since translating is done by you, whatever languages you master are all supported.

**Comment by BSVogler** [comment]
Okay, thank you. You could put your answer in the readme. :)
